//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xServerLog {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xServerControl.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure to Add a New Job Instruction?.
        /// </summary>
        internal static string MsgAgreetoAddNewRecord {
            get {
                return ResourceManager.GetString("MsgAgreetoAddNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure to Cancel the Operation?.
        /// </summary>
        internal static string MsgAgreetoCancel {
            get {
                return ResourceManager.GetString("MsgAgreetoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure that you want to delete this Job Instruction?.
        /// </summary>
        internal static string MsgAgreetoDeleteNewRecord {
            get {
                return ResourceManager.GetString("MsgAgreetoDeleteNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure to Save the new Job Instruction?.
        /// </summary>
        internal static string MsgAgreetoSaveNewRecord {
            get {
                return ResourceManager.GetString("MsgAgreetoSaveNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All the Active Jobs was executed and the elapsetime is.
        /// </summary>
        internal static string MsgAllActiveJobElapseTime {
            get {
                return ResourceManager.GetString("MsgAllActiveJobElapseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Actions Log Path, created in.
        /// </summary>
        internal static string MsgAppActLogPathCreated {
            get {
                return ResourceManager.GetString("MsgAppActLogPathCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Actions Log Path Found in.
        /// </summary>
        internal static string MsgAppActLogPathFound {
            get {
                return ResourceManager.GetString("MsgAppActLogPathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Actions Log Path Not Found in.
        /// </summary>
        internal static string MsgAppActLogPathNotFound {
            get {
                return ResourceManager.GetString("MsgAppActLogPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Base Log Path, created in.
        /// </summary>
        internal static string MsgAppBaseLogPathCreated {
            get {
                return ResourceManager.GetString("MsgAppBaseLogPathCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Base Log Path Found in.
        /// </summary>
        internal static string MsgAppBaseLogPathFound {
            get {
                return ResourceManager.GetString("MsgAppBaseLogPathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Base Log Path Not Found in.
        /// </summary>
        internal static string MsgAppBaseLogPathNotFound {
            get {
                return ResourceManager.GetString("MsgAppBaseLogPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application License status is Not Valid or maybe corrupcted, please verify!!!.
        /// </summary>
        internal static string MsgAppLicNotValid {
            get {
                return ResourceManager.GetString("MsgAppLicNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application running out of the active license period....
        /// </summary>
        internal static string MsgAppLicOutOfPeriod {
            get {
                return ResourceManager.GetString("MsgAppLicOutOfPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Log file.
        /// </summary>
        internal static string MsgAppLogFile {
            get {
                return ResourceManager.GetString("MsgAppLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Log file created with success!!!.
        /// </summary>
        internal static string MsgAppLogFileCrtdSuccess {
            get {
                return ResourceManager.GetString("MsgAppLogFileCrtdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application System Log file:.
        /// </summary>
        internal static string MsgAppSysLogFile {
            get {
                return ResourceManager.GetString("MsgAppSysLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application System Log Path, created in.
        /// </summary>
        internal static string MsgAppSysLogPathCreated {
            get {
                return ResourceManager.GetString("MsgAppSysLogPathCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application System Log Path Found in.
        /// </summary>
        internal static string MsgAppSysLogPathFound {
            get {
                return ResourceManager.GetString("MsgAppSysLogPathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application System Log Path Not Found in.
        /// </summary>
        internal static string MsgAppSysLogPathNotFound {
            get {
                return ResourceManager.GetString("MsgAppSysLogPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Terminated!!!.
        /// </summary>
        internal static string MsgAppTerminated {
            get {
                return ResourceManager.GetString("MsgAppTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Working Path, created in.
        /// </summary>
        internal static string MsgAppWrkLogPathCreated {
            get {
                return ResourceManager.GetString("MsgAppWrkLogPathCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Working Path Found in.
        /// </summary>
        internal static string MsgAppWrkLogPathFound {
            get {
                return ResourceManager.GetString("MsgAppWrkLogPathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Working Path Not Found in.
        /// </summary>
        internal static string MsgAppWrkLogPathNotFound {
            get {
                return ResourceManager.GetString("MsgAppWrkLogPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot connect to server.  Contact administrator!.
        /// </summary>
        internal static string MsgCannotConServer {
            get {
                return ResourceManager.GetString("MsgCannotConServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cleanup log routine was executed, see App logfile for more details..
        /// </summary>
        internal static string MsgCleanUpRoutine {
            get {
                return ResourceManager.GetString("MsgCleanUpRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connection DB File.
        /// </summary>
        internal static string MsgConnDBFile {
            get {
                return ResourceManager.GetString("MsgConnDBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connecting with the Registration Server....
        /// </summary>
        internal static string MsgConnRemServer {
            get {
                return ResourceManager.GetString("MsgConnRemServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Continuing the log file....
        /// </summary>
        internal static string MsgContLogFile {
            get {
                return ResourceManager.GetString("MsgContLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a created with success !!!.
        /// </summary>
        internal static string MsgCrtdWithSuccess {
            get {
                return ResourceManager.GetString("MsgCrtdWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a day(s), all the file(s) with creation or modification date less then.
        /// </summary>
        internal static string MsgDayAllFilesWillbe {
            get {
                return ResourceManager.GetString("MsgDayAllFilesWillbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a day(s), all the file(s) will be.
        /// </summary>
        internal static string MsgDayAllFilesWillbeExec {
            get {
                return ResourceManager.GetString("MsgDayAllFilesWillbeExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DaysLeft.
        /// </summary>
        internal static string MsgDaysLeft {
            get {
                return ResourceManager.GetString("MsgDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DB connection file not found... starting to create!.
        /// </summary>
        internal static string MsgDBConnFileNotFound {
            get {
                return ResourceManager.GetString("MsgDBConnFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definition File:.
        /// </summary>
        internal static string MsgDefFile {
            get {
                return ResourceManager.GetString("MsgDefFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definition file not found... starting to create!.
        /// </summary>
        internal static string MsgDefFileNotFound {
            get {
                return ResourceManager.GetString("MsgDefFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definition file not found... The Application will be Closed!.
        /// </summary>
        internal static string MsgDefFileNotFoundExit {
            get {
                return ResourceManager.GetString("MsgDefFileNotFoundExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a End of Job Processing at:.
        /// </summary>
        internal static string MsgEndJobProcAt {
            get {
                return ResourceManager.GetString("MsgEndJobProcAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot determine operating system!.
        /// </summary>
        internal static string MsgErrCannotDetcOS {
            get {
                return ResourceManager.GetString("MsgErrCannotDetcOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error closing the connection.  Contact administrator.
        /// </summary>
        internal static string MsgErrClosConnection {
            get {
                return ResourceManager.GetString("MsgErrClosConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error creating Application Action Log Folder in.
        /// </summary>
        internal static string MsgErrCrtActLogFolder {
            get {
                return ResourceManager.GetString("MsgErrCrtActLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error creating the DB connection.
        /// </summary>
        internal static string MsgErrCrtDBConn {
            get {
                return ResourceManager.GetString("MsgErrCrtDBConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error creating the DB connection file:.
        /// </summary>
        internal static string MsgErrCrtDBConnFile {
            get {
                return ResourceManager.GetString("MsgErrCrtDBConnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error creating the definition file:.
        /// </summary>
        internal static string MsgErrCrtDefFile {
            get {
                return ResourceManager.GetString("MsgErrCrtDefFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error creating license file, please verify!!!.
        /// </summary>
        internal static string MsgErrCrtLicenseFile {
            get {
                return ResourceManager.GetString("MsgErrCrtLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error creating System Log Folder in.
        /// </summary>
        internal static string MsgErrCrtSysLogFolder {
            get {
                return ResourceManager.GetString("MsgErrCrtSysLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error creating Working Folder in.
        /// </summary>
        internal static string MsgErrCrtWrkLogFolder {
            get {
                return ResourceManager.GetString("MsgErrCrtWrkLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only one log type can be selected..
        /// </summary>
        internal static string MsgErrOnlyOneLog {
            get {
                return ResourceManager.GetString("MsgErrOnlyOneLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error generating the files:.
        /// </summary>
        internal static string MsgErrorGenFiles {
            get {
                return ResourceManager.GetString("MsgErrorGenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error processing file:.
        /// </summary>
        internal static string MsgErrProcFile {
            get {
                return ResourceManager.GetString("MsgErrProcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to copy the file:.
        /// </summary>
        internal static string MsgErrTryCopyFile {
            get {
                return ResourceManager.GetString("MsgErrTryCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to download the file:.
        /// </summary>
        internal static string MsgErrTryDownFile {
            get {
                return ResourceManager.GetString("MsgErrTryDownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to move the file:.
        /// </summary>
        internal static string MsgErrTryMoveFile {
            get {
                return ResourceManager.GetString("MsgErrTryMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to remove or download the file:.
        /// </summary>
        internal static string MsgErrTryRemDownFile {
            get {
                return ResourceManager.GetString("MsgErrTryRemDownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to remove the file:.
        /// </summary>
        internal static string MsgErrTryRemFile {
            get {
                return ResourceManager.GetString("MsgErrTryRemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to rename the file:.
        /// </summary>
        internal static string MsgErrTryRenFile {
            get {
                return ResourceManager.GetString("MsgErrTryRenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to Upload the file:.
        /// </summary>
        internal static string MsgErrTryUpFile {
            get {
                return ResourceManager.GetString("MsgErrTryUpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to Upload and delete the file:.
        /// </summary>
        internal static string MsgErrTryUpldFile {
            get {
                return ResourceManager.GetString("MsgErrTryUpldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error trying to zip the file:.
        /// </summary>
        internal static string MsgErrTryZipfile {
            get {
                return ResourceManager.GetString("MsgErrTryZipfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error unable to Restore!.
        /// </summary>
        internal static string MsgErrUnableToRestore {
            get {
                return ResourceManager.GetString("MsgErrUnableToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error unable to backup!.
        /// </summary>
        internal static string MsgErrUnbToBackup {
            get {
                return ResourceManager.GetString("MsgErrUnbToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fatal Error!!! Log Folder Not Found or No Permission to access !!!.
        /// </summary>
        internal static string MsgFatalErrorlogFolder {
            get {
                return ResourceManager.GetString("MsgFatalErrorlogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fatal error sending email message, look the log line below.
        /// </summary>
        internal static string MsgFatalErrorSendMail {
            get {
                return ResourceManager.GetString("MsgFatalErrorSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File in the Exception folder:.
        /// </summary>
        internal static string MsgFileExcpFolder {
            get {
                return ResourceManager.GetString("MsgFileExcpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Files will be generated in.
        /// </summary>
        internal static string MsgFileWillBeGenerete {
            get {
                return ResourceManager.GetString("MsgFileWillBeGenerete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a file handle and action..
        /// </summary>
        internal static string MsgFlHandleAction {
            get {
                return ResourceManager.GetString("MsgFlHandleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid username/password, please try again.
        /// </summary>
        internal static string MsgInvUserPass {
            get {
                return ResourceManager.GetString("MsgInvUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Routine is running in Run Once execution, verify the action log for more details....
        /// </summary>
        internal static string MsgJobRnnOnce {
            get {
                return ResourceManager.GetString("MsgJobRnnOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Routine is running, verify the action log for more details....
        /// </summary>
        internal static string MsgJobRnnVerify {
            get {
                return ResourceManager.GetString("MsgJobRnnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You reached the last item of the list!.
        /// </summary>
        internal static string MsgReachEndOf {
            get {
                return ResourceManager.GetString("MsgReachEndOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You reached the first item of the list!.
        /// </summary>
        internal static string MsgReachFirstOf {
            get {
                return ResourceManager.GetString("MsgReachFirstOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running in a Computer with the follow informations:.
        /// </summary>
        internal static string MsgRungComputer {
            get {
                return ResourceManager.GetString("MsgRungComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Instruction job file Saved with success!.
        /// </summary>
        internal static string MsgSaveSuccess {
            get {
                return ResourceManager.GetString("MsgSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server Started and are up and running....
        /// </summary>
        internal static string MsgServerStarted {
            get {
                return ResourceManager.GetString("MsgServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This Job are running for.
        /// </summary>
        internal static string MsgThiJobRunning {
            get {
                return ResourceManager.GetString("MsgThiJobRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please verify the selected box!.
        /// </summary>
        internal static string MsgVerifySelectBox {
            get {
                return ResourceManager.GetString("MsgVerifySelectBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verify the exception entry.
        /// </summary>
        internal static string MsgVrfExcEntry {
            get {
                return ResourceManager.GetString("MsgVrfExcEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About the Application.
        /// </summary>
        internal static string StrAbout {
            get {
                return ResourceManager.GetString("StrAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a action..
        /// </summary>
        internal static string StrAction {
            get {
                return ResourceManager.GetString("StrAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Actions Log file:.
        /// </summary>
        internal static string StrActionLogFile {
            get {
                return ResourceManager.GetString("StrActionLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Action Log Files.
        /// </summary>
        internal static string StrActionLogfiles {
            get {
                return ResourceManager.GetString("StrActionLogfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Action Log History.
        /// </summary>
        internal static string StrActionLogHistory {
            get {
                return ResourceManager.GetString("StrActionLogHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Action type.
        /// </summary>
        internal static string StrActionType {
            get {
                return ResourceManager.GetString("StrActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copy.
        /// </summary>
        internal static string StrActionTypeCopy {
            get {
                return ResourceManager.GetString("StrActionTypeCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Move.
        /// </summary>
        internal static string StrActionTypeMov {
            get {
                return ResourceManager.GetString("StrActionTypeMov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rename.
        /// </summary>
        internal static string StrActionTypeRen {
            get {
                return ResourceManager.GetString("StrActionTypeRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Zip.
        /// </summary>
        internal static string StrActionTypeZip {
            get {
                return ResourceManager.GetString("StrActionTypeZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Zip and Delete.
        /// </summary>
        internal static string StrActionTypeZipDel {
            get {
                return ResourceManager.GetString("StrActionTypeZipDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Active Jobs:.
        /// </summary>
        internal static string StrActiveJobs {
            get {
                return ResourceManager.GetString("StrActiveJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a and the Target folder is.
        /// </summary>
        internal static string StrAndTargetIs {
            get {
                return ResourceManager.GetString("StrAndTargetIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application..
        /// </summary>
        internal static string StrApplication {
            get {
                return ResourceManager.GetString("StrApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application Name.
        /// </summary>
        internal static string StrAppName {
            get {
                return ResourceManager.GetString("StrAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Statistics.
        /// </summary>
        internal static string StrbrStatistic {
            get {
                return ResourceManager.GetString("StrbrStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add.
        /// </summary>
        internal static string StrbtAdd {
            get {
                return ResourceManager.GetString("StrbtAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Back.
        /// </summary>
        internal static string StrbtBack {
            get {
                return ResourceManager.GetString("StrbtBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        internal static string StrbtCancel {
            get {
                return ResourceManager.GetString("StrbtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        internal static string StrbtClose {
            get {
                return ResourceManager.GetString("StrbtClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string StrbtDelete {
            get {
                return ResourceManager.GetString("StrbtDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a First.
        /// </summary>
        internal static string StrbtFirst {
            get {
                return ResourceManager.GetString("StrbtFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instructions File.
        /// </summary>
        internal static string StrbtInstruction {
            get {
                return ResourceManager.GetString("StrbtInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instructions Builder.
        /// </summary>
        internal static string StrbtInstructionBuilder {
            get {
                return ResourceManager.GetString("StrbtInstructionBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Last.
        /// </summary>
        internal static string StrbtLast {
            get {
                return ResourceManager.GetString("StrbtLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Load.
        /// </summary>
        internal static string StrbtLoad {
            get {
                return ResourceManager.GetString("StrbtLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log History.
        /// </summary>
        internal static string StrbtLogHistory {
            get {
                return ResourceManager.GetString("StrbtLogHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next.
        /// </summary>
        internal static string StrbtNext {
            get {
                return ResourceManager.GetString("StrbtNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Run.
        /// </summary>
        internal static string StrbtRun {
            get {
                return ResourceManager.GetString("StrbtRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Run Once.
        /// </summary>
        internal static string StrbtRunOnce {
            get {
                return ResourceManager.GetString("StrbtRunOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string StrbtSave {
            get {
                return ResourceManager.GetString("StrbtSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop.
        /// </summary>
        internal static string StrbtStop {
            get {
                return ResourceManager.GetString("StrbtStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please click in History Button to see the log informations....
        /// </summary>
        internal static string StrClickInHistoryBt {
            get {
                return ResourceManager.GetString("StrClickInHistoryBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close the application.
        /// </summary>
        internal static string StrCloseApplication {
            get {
                return ResourceManager.GetString("StrCloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close the window.
        /// </summary>
        internal static string StrCloseWindow {
            get {
                return ResourceManager.GetString("StrCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Computer Name:.
        /// </summary>
        internal static string StrComputerName {
            get {
                return ResourceManager.GetString("StrComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copying File.
        /// </summary>
        internal static string StrCopyFile {
            get {
                return ResourceManager.GetString("StrCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copy time:.
        /// </summary>
        internal static string StrCopyTime {
            get {
                return ResourceManager.GetString("StrCopyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a created!!!.
        /// </summary>
        internal static string StrCreated {
            get {
                return ResourceManager.GetString("StrCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string StrDelete {
            get {
                return ResourceManager.GetString("StrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete time:.
        /// </summary>
        internal static string StrDeleteTime {
            get {
                return ResourceManager.GetString("StrDeleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Destination ZIP file will be.
        /// </summary>
        internal static string StrDestZipFilewillbe {
            get {
                return ResourceManager.GetString("StrDestZipFilewillbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downloading File:.
        /// </summary>
        internal static string StrDwnFile {
            get {
                return ResourceManager.GetString("StrDwnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        internal static string StrEmail {
            get {
                return ResourceManager.GetString("StrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This e-mail was generated by xfileActions Handle and is part of the monitoring module..
        /// </summary>
        internal static string StrEmailGeneratedBy {
            get {
                return ResourceManager.GetString("StrEmailGeneratedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error :.
        /// </summary>
        internal static string StrError {
            get {
                return ResourceManager.GetString("StrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error Number:.
        /// </summary>
        internal static string StrErrorNumber {
            get {
                return ResourceManager.GetString("StrErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclamation.
        /// </summary>
        internal static string StrExclamation {
            get {
                return ResourceManager.GetString("StrExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exception Folder.
        /// </summary>
        internal static string StrExcpFolder {
            get {
                return ResourceManager.GetString("StrExcpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exception message:.
        /// </summary>
        internal static string StrExcpMessage {
            get {
                return ResourceManager.GetString("StrExcpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Exception Source folder is.
        /// </summary>
        internal static string StrExcSourceFolderIs {
            get {
                return ResourceManager.GetString("StrExcSourceFolderIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a executed at.
        /// </summary>
        internal static string StrExecutedAt {
            get {
                return ResourceManager.GetString("StrExecutedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Execution In:.
        /// </summary>
        internal static string StrExecutionIn {
            get {
                return ResourceManager.GetString("StrExecutionIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expire in.
        /// </summary>
        internal static string StrExpireIn {
            get {
                return ResourceManager.GetString("StrExpireIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a file(s) found !!!.
        /// </summary>
        internal static string StrFilesFound {
            get {
                return ResourceManager.GetString("StrFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a with the extension.
        /// </summary>
        internal static string StrFileWithExtension {
            get {
                return ResourceManager.GetString("StrFileWithExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Folder Exception.
        /// </summary>
        internal static string StrFolderException {
            get {
                return ResourceManager.GetString("StrFolderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Folder Informations.
        /// </summary>
        internal static string StrFolderInformations {
            get {
                return ResourceManager.GetString("StrFolderInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a for.
        /// </summary>
        internal static string StrFor {
            get {
                return ResourceManager.GetString("StrFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ftp Delete time:.
        /// </summary>
        internal static string StrFtpDeleteTime {
            get {
                return ResourceManager.GetString("StrFtpDeleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download Delete time:.
        /// </summary>
        internal static string StrFtpDownDelTime {
            get {
                return ResourceManager.GetString("StrFtpDownDelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download time:.
        /// </summary>
        internal static string StrFtpDownTime {
            get {
                return ResourceManager.GetString("StrFtpDownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Source IP Address.
        /// </summary>
        internal static string StrFtpSourceAddress {
            get {
                return ResourceManager.GetString("StrFtpSourceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Source Folder.
        /// </summary>
        internal static string StrFtpSourceFolder {
            get {
                return ResourceManager.GetString("StrFtpSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Source Informations.
        /// </summary>
        internal static string StrFtpSourceInformations {
            get {
                return ResourceManager.GetString("StrFtpSourceInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Source Pass.
        /// </summary>
        internal static string StrFtpSourcePass {
            get {
                return ResourceManager.GetString("StrFtpSourcePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Source IP Port.
        /// </summary>
        internal static string StrFtpSourcePort {
            get {
                return ResourceManager.GetString("StrFtpSourcePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Source User.
        /// </summary>
        internal static string StrFtpSourceUser {
            get {
                return ResourceManager.GetString("StrFtpSourceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The FTP Source folder is.
        /// </summary>
        internal static string StrFtpSrcFolderis {
            get {
                return ResourceManager.GetString("StrFtpSrcFolderis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Target Folder.
        /// </summary>
        internal static string StrFtpTargetFolder {
            get {
                return ResourceManager.GetString("StrFtpTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Target Informations.
        /// </summary>
        internal static string StrFtpTargetInformations {
            get {
                return ResourceManager.GetString("StrFtpTargetInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The FTP Target folder is.
        /// </summary>
        internal static string StrFtpTgtFolderis {
            get {
                return ResourceManager.GetString("StrFtpTgtFolderis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Target IP Address.
        /// </summary>
        internal static string StrFtpTrgtAddress {
            get {
                return ResourceManager.GetString("StrFtpTrgtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Target Pass.
        /// </summary>
        internal static string StrFtpTrgtPass {
            get {
                return ResourceManager.GetString("StrFtpTrgtPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Target IP Port.
        /// </summary>
        internal static string StrFtpTrgtPort {
            get {
                return ResourceManager.GetString("StrFtpTrgtPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FTP Target User.
        /// </summary>
        internal static string StrFtpTrgtUser {
            get {
                return ResourceManager.GetString("StrFtpTrgtUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Upload Delete time:.
        /// </summary>
        internal static string StrFtpUpDeleteTime {
            get {
                return ResourceManager.GetString("StrFtpUpDeleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Upload time:.
        /// </summary>
        internal static string StrFtpUploadtime {
            get {
                return ResourceManager.GetString("StrFtpUploadtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inactive Jobs:.
        /// </summary>
        internal static string StrInactiveJobs {
            get {
                return ResourceManager.GetString("StrInactiveJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Information.
        /// </summary>
        internal static string StrInformation {
            get {
                return ResourceManager.GetString("StrInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a in FTP Server.
        /// </summary>
        internal static string StrInFtpServer {
            get {
                return ResourceManager.GetString("StrInFtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instruction file Manager.
        /// </summary>
        internal static string StrInstFileManager {
            get {
                return ResourceManager.GetString("StrInstFileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instruction file view.
        /// </summary>
        internal static string StrInstFileView {
            get {
                return ResourceManager.GetString("StrInstFileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instruction File:.
        /// </summary>
        internal static string StrInstructionFileName {
            get {
                return ResourceManager.GetString("StrInstructionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instructions Maintenance.
        /// </summary>
        internal static string StrInstructionMaintenance {
            get {
                return ResourceManager.GetString("StrInstructionMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Instructions List.
        /// </summary>
        internal static string StrInstructionsList {
            get {
                return ResourceManager.GetString("StrInstructionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job.
        /// </summary>
        internal static string StrJob {
            get {
                return ResourceManager.GetString("StrJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Action Informations.
        /// </summary>
        internal static string StrJobActInformations {
            get {
                return ResourceManager.GetString("StrJobActInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This Job is alreally deleted!.
        /// </summary>
        internal static string StrJobAllreallyDelete {
            get {
                return ResourceManager.GetString("StrJobAllreallyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Execution Results.
        /// </summary>
        internal static string StrJobExecResult {
            get {
                return ResourceManager.GetString("StrJobExecResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Execution Interval:.
        /// </summary>
        internal static string StrJobExecutionInterval {
            get {
                return ResourceManager.GetString("StrJobExecutionInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Executions List.
        /// </summary>
        internal static string StrJobExecutionList {
            get {
                return ResourceManager.GetString("StrJobExecutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Instructions.
        /// </summary>
        internal static string StrJobInstructions {
            get {
                return ResourceManager.GetString("StrJobInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Mode.
        /// </summary>
        internal static string StrJobModo {
            get {
                return ResourceManager.GetString("StrJobModo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job Name.
        /// </summary>
        internal static string StrJobName {
            get {
                return ResourceManager.GetString("StrJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jobs.
        /// </summary>
        internal static string StrJobs {
            get {
                return ResourceManager.GetString("StrJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job execution started at:.
        /// </summary>
        internal static string StrJobStart {
            get {
                return ResourceManager.GetString("StrJobStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job State:.
        /// </summary>
        internal static string StrJobState {
            get {
                return ResourceManager.GetString("StrJobState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a License days remaing.
        /// </summary>
        internal static string StrLicDayRemaing {
            get {
                return ResourceManager.GetString("StrLicDayRemaing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a License.
        /// </summary>
        internal static string StrLicense {
            get {
                return ResourceManager.GetString("StrLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a License Informations.
        /// </summary>
        internal static string StrLicenseInformations {
            get {
                return ResourceManager.GetString("StrLicenseInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a License File:.
        /// </summary>
        internal static string StrLicFile {
            get {
                return ResourceManager.GetString("StrLicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a License File not found... starting to create!.
        /// </summary>
        internal static string StrLicFileNotFound {
            get {
                return ResourceManager.GetString("StrLicFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a License Informations validated.
        /// </summary>
        internal static string StrLicInfValid {
            get {
                return ResourceManager.GetString("StrLicInfValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a License Initial date.
        /// </summary>
        internal static string StrLicIniDate {
            get {
                return ResourceManager.GetString("StrLicIniDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a License file loaded with success, starting validation process!!!.
        /// </summary>
        internal static string StrLicLoadSuc {
            get {
                return ResourceManager.GetString("StrLicLoadSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Licensed to:.
        /// </summary>
        internal static string StrLicTo {
            get {
                return ResourceManager.GetString("StrLicTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Loaded!.
        /// </summary>
        internal static string StrLoaded {
            get {
                return ResourceManager.GetString("StrLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log files cleanup routine was executed....
        /// </summary>
        internal static string StrLogCleanexec {
            get {
                return ResourceManager.GetString("StrLogCleanexec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log created by.
        /// </summary>
        internal static string StrLogCreatedby {
            get {
                return ResourceManager.GetString("StrLogCreatedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log file name:.
        /// </summary>
        internal static string StrLogFileName {
            get {
                return ResourceManager.GetString("StrLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log Informations.
        /// </summary>
        internal static string StrLogInformations {
            get {
                return ResourceManager.GetString("StrLogInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log Mode.
        /// </summary>
        internal static string StrLogMod {
            get {
                return ResourceManager.GetString("StrLogMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maximize the window.
        /// </summary>
        internal static string StrMaximizeWindow {
            get {
                return ResourceManager.GetString("StrMaximizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Minimize the window.
        /// </summary>
        internal static string StrMinimizeWindow {
            get {
                return ResourceManager.GetString("StrMinimizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mode.
        /// </summary>
        internal static string StrMode {
            get {
                return ResourceManager.GetString("StrMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Move time:.
        /// </summary>
        internal static string StrMoveTime {
            get {
                return ResourceManager.GetString("StrMoveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Moving File.
        /// </summary>
        internal static string StrMovFile {
            get {
                return ResourceManager.GetString("StrMovFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not Found!!!.
        /// </summary>
        internal static string StrNoFound {
            get {
                return ResourceManager.GetString("StrNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a not found, starting to create !!!.
        /// </summary>
        internal static string StrNotFndStrtCreate {
            get {
                return ResourceManager.GetString("StrNotFndStrtCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notification Icon: xfileActions.
        /// </summary>
        internal static string StrNotificationIcon {
            get {
                return ResourceManager.GetString("StrNotificationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not Licensed - in trial period.
        /// </summary>
        internal static string StrNotLicensed {
            get {
                return ResourceManager.GetString("StrNotLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Number of executions:.
        /// </summary>
        internal static string StrNumberOfExecution {
            get {
                return ResourceManager.GetString("StrNumberOfExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Number of Jobs:.
        /// </summary>
        internal static string StrNumberofJobs {
            get {
                return ResourceManager.GetString("StrNumberofJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operation System:.
        /// </summary>
        internal static string StrOperationSystem {
            get {
                return ResourceManager.GetString("StrOperationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a and the pattern is.
        /// </summary>
        internal static string StrPatternIs {
            get {
                return ResourceManager.GetString("StrPatternIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Port.
        /// </summary>
        internal static string StrPort {
            get {
                return ResourceManager.GetString("StrPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Port:.
        /// </summary>
        internal static string StrPort2Points {
            get {
                return ResourceManager.GetString("StrPort2Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processing Job named:.
        /// </summary>
        internal static string StrProcJobName {
            get {
                return ResourceManager.GetString("StrProcJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor Platform: 64 Bits.
        /// </summary>
        internal static string StrProcPlatForm {
            get {
                return ResourceManager.GetString("StrProcPlatForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registered!... Done!.
        /// </summary>
        internal static string StrRegDone {
            get {
                return ResourceManager.GetString("StrRegDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration File.
        /// </summary>
        internal static string StrRegFile {
            get {
                return ResourceManager.GetString("StrRegFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration file is correct !!!.
        /// </summary>
        internal static string StrRegFileCorrect {
            get {
                return ResourceManager.GetString("StrRegFileCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration file Not Found, please verify!.
        /// </summary>
        internal static string StrRegfileNotFound {
            get {
                return ResourceManager.GetString("StrRegfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration Informations validated.
        /// </summary>
        internal static string StrRegInfValidated {
            get {
                return ResourceManager.GetString("StrRegInfValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration Process was made in the remote server... done!.
        /// </summary>
        internal static string StrRegProcMadeRemote {
            get {
                return ResourceManager.GetString("StrRegProcMadeRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration process was made with success!.
        /// </summary>
        internal static string StrRegProcMadeSucc {
            get {
                return ResourceManager.GetString("StrRegProcMadeSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rename time:.
        /// </summary>
        internal static string StrRenameTime {
            get {
                return ResourceManager.GetString("StrRenameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Renaming File.
        /// </summary>
        internal static string StrRenFile {
            get {
                return ResourceManager.GetString("StrRenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restore the window.
        /// </summary>
        internal static string StrRestoreWindow {
            get {
                return ResourceManager.GetString("StrRestoreWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Right-click on the icon for more options..
        /// </summary>
        internal static string StrRightClickOnIcon {
            get {
                return ResourceManager.GetString("StrRightClickOnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Removing File.
        /// </summary>
        internal static string StrRmvFile {
            get {
                return ResourceManager.GetString("StrRmvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Routine was defined as.
        /// </summary>
        internal static string StrRoutine {
            get {
                return ResourceManager.GetString("StrRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a and are running with status.
        /// </summary>
        internal static string StrRungWithStatus {
            get {
                return ResourceManager.GetString("StrRungWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running....
        /// </summary>
        internal static string StrRunning {
            get {
                return ResourceManager.GetString("StrRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Run Once....
        /// </summary>
        internal static string StrRunOne {
            get {
                return ResourceManager.GetString("StrRunOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Security Log Files.
        /// </summary>
        internal static string StrSecLogFilesInformations {
            get {
                return ResourceManager.GetString("StrSecLogFilesInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send Email On Action.
        /// </summary>
        internal static string StrSendMailOn {
            get {
                return ResourceManager.GetString("StrSendMailOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serial Number:.
        /// </summary>
        internal static string StrSerialNumber {
            get {
                return ResourceManager.GetString("StrSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Source Folder.
        /// </summary>
        internal static string StrSouceFolder {
            get {
                return ResourceManager.GetString("StrSouceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Source Folder.
        /// </summary>
        internal static string StrSourceFolder {
            get {
                return ResourceManager.GetString("StrSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Source folder is.
        /// </summary>
        internal static string StrSourceFolderis {
            get {
                return ResourceManager.GetString("StrSourceFolderis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Source Host.
        /// </summary>
        internal static string StrSourceHost {
            get {
                return ResourceManager.GetString("StrSourceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Source Pass.
        /// </summary>
        internal static string StrSourcePass {
            get {
                return ResourceManager.GetString("StrSourcePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Source User.
        /// </summary>
        internal static string StrSourceUser {
            get {
                return ResourceManager.GetString("StrSourceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string StrStatus {
            get {
                return ResourceManager.GetString("StrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stopped....
        /// </summary>
        internal static string StrStopped {
            get {
                return ResourceManager.GetString("StrStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System Log file:.
        /// </summary>
        internal static string StrSyslogFile {
            get {
                return ResourceManager.GetString("StrSyslogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System Started.
        /// </summary>
        internal static string StrSysStarted {
            get {
                return ResourceManager.GetString("StrSysStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System Initiated!.
        /// </summary>
        internal static string StrSysteminit {
            get {
                return ResourceManager.GetString("StrSysteminit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System Log Files.
        /// </summary>
        internal static string StrSystemLogFiles {
            get {
                return ResourceManager.GetString("StrSystemLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System is running in.
        /// </summary>
        internal static string StrSystemRunning {
            get {
                return ResourceManager.GetString("StrSystemRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System running in the active license period &lt;.
        /// </summary>
        internal static string StrSystemRunningActiveLicPer {
            get {
                return ResourceManager.GetString("StrSystemRunningActiveLicPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System started and are up and running... since.
        /// </summary>
        internal static string StrSystemStartedandUpRunn {
            get {
                return ResourceManager.GetString("StrSystemStartedandUpRunn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Target Folder.
        /// </summary>
        internal static string StrTargetFolder {
            get {
                return ResourceManager.GetString("StrTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Target folder is.
        /// </summary>
        internal static string StrTargetFolderis {
            get {
                return ResourceManager.GetString("StrTargetFolderis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Target Host.
        /// </summary>
        internal static string StrTargetHost {
            get {
                return ResourceManager.GetString("StrTargetHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Target Pass.
        /// </summary>
        internal static string StrTargetPass {
            get {
                return ResourceManager.GetString("StrTargetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Target User.
        /// </summary>
        internal static string StrTargetUser {
            get {
                return ResourceManager.GetString("StrTargetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Target patern is.
        /// </summary>
        internal static string StrTgtPaternis {
            get {
                return ResourceManager.GetString("StrTgtPaternis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Time To Live.
        /// </summary>
        internal static string StrTimeToLive {
            get {
                return ResourceManager.GetString("StrTimeToLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to.
        /// </summary>
        internal static string StrTo {
            get {
                return ResourceManager.GetString("StrTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total Execution in time:.
        /// </summary>
        internal static string StrTotalExecTime {
            get {
                return ResourceManager.GetString("StrTotalExecTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total files:.
        /// </summary>
        internal static string StrTotFiles {
            get {
                return ResourceManager.GetString("StrTotFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total files in exception folder:.
        /// </summary>
        internal static string StrTtFilesExcFolder {
            get {
                return ResourceManager.GetString("StrTtFilesExcFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total files with error to processing:.
        /// </summary>
        internal static string StrTtFileswithError {
            get {
                return ResourceManager.GetString("StrTtFileswithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TTL.
        /// </summary>
        internal static string StrTTL {
            get {
                return ResourceManager.GetString("StrTTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Time to Live defined for the file(s) is.
        /// </summary>
        internal static string StrTtlDefinfor {
            get {
                return ResourceManager.GetString("StrTtlDefinfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uploading File:.
        /// </summary>
        internal static string StrUplFile {
            get {
                return ResourceManager.GetString("StrUplFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valid To:.
        /// </summary>
        internal static string StrValidTo {
            get {
                return ResourceManager.GetString("StrValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version.
        /// </summary>
        internal static string StrVersion {
            get {
                return ResourceManager.GetString("StrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verify Sub Folders?.
        /// </summary>
        internal static string StrVerSubFolders {
            get {
                return ResourceManager.GetString("StrVerSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Waiting....
        /// </summary>
        internal static string StrWaiting {
            get {
                return ResourceManager.GetString("StrWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        internal static string StrWarning {
            get {
                return ResourceManager.GetString("StrWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a was created with Success!.
        /// </summary>
        internal static string StrWasCreatWithSuccess {
            get {
                return ResourceManager.GetString("StrWasCreatWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a was deleted!.
        /// </summary>
        internal static string StrWasDeleted {
            get {
                return ResourceManager.GetString("StrWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a was executed and the elapsed time is.
        /// </summary>
        internal static string StrWasExctElapse {
            get {
                return ResourceManager.GetString("StrWasExctElapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a was executed with Error!.
        /// </summary>
        internal static string StrWasExctError {
            get {
                return ResourceManager.GetString("StrWasExctError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wildcard.
        /// </summary>
        internal static string StrWildCard {
            get {
                return ResourceManager.GetString("StrWildCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wildcard on excep....
        /// </summary>
        internal static string StrWildcardOnException {
            get {
                return ResourceManager.GetString("StrWildcardOnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a will be.
        /// </summary>
        internal static string StrWillBe {
            get {
                return ResourceManager.GetString("StrWillBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a and will be executed....
        /// </summary>
        internal static string StrWillBeExecuted {
            get {
                return ResourceManager.GetString("StrWillBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a and will Not be executed....
        /// </summary>
        internal static string StrWillBeNotExecuted {
            get {
                return ResourceManager.GetString("StrWillBeNotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a with the error below..
        /// </summary>
        internal static string StrWithErrorBelow {
            get {
                return ResourceManager.GetString("StrWithErrorBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a with the pattern iqual.
        /// </summary>
        internal static string StrWithPatternIqual {
            get {
                return ResourceManager.GetString("StrWithPatternIqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a with success..
        /// </summary>
        internal static string StrWithSuccess {
            get {
                return ResourceManager.GetString("StrWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WorkingSet Memory:.
        /// </summary>
        internal static string StrWkSetMemory {
            get {
                return ResourceManager.GetString("StrWkSetMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WildCard on Exception Folder.
        /// </summary>
        internal static string StrWlcOnExcFolder {
            get {
                return ResourceManager.GetString("StrWlcOnExcFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WildCard on Source.
        /// </summary>
        internal static string StrWlcOnSource {
            get {
                return ResourceManager.GetString("StrWlcOnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WildCard on Target.
        /// </summary>
        internal static string StrWlcOnTarget {
            get {
                return ResourceManager.GetString("StrWlcOnTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Zip Delete time:.
        /// </summary>
        internal static string StrZipDeleteTime {
            get {
                return ResourceManager.GetString("StrZipDeleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ziping File.
        /// </summary>
        internal static string StrZipFile {
            get {
                return ResourceManager.GetString("StrZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Zip Name.
        /// </summary>
        internal static string StrZipName {
            get {
                return ResourceManager.GetString("StrZipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Zip time:.
        /// </summary>
        internal static string StrZipTime {
            get {
                return ResourceManager.GetString("StrZipTime", resourceCulture);
            }
        }
    }
}
